config/routes.rb
Rails.application.routes.draw do

  root "videos#index"

  get "/videos" => "videos#index"

  get "/videos/new" => "videos#new"

  post "/videos" => "videos#create"

end

app/models/video.rb
class Video < ActiveRecord::Base

  validates :embed_url, uniqueness: true, presence: true
  validates :title, presence: true


  def youtube_link
    "https://youtu.be/#{self.embed_url}"
  end

  def embed_link
    "https://www.youtube.com/embed/#{self.embed_url}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
    @videos = Video.all
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(self.video_params)

    # redirect
    if @video.save
      redirect_to videos_path
    # if it fails, just re-render the form
    else
      render :new
    end
  end

  def video_params
    params.require(:video).permit(:title, :embed_url, :released_on, :featured_artists)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mr Worldwide TV</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1><%= link_to "Mr. Worldwide TV", videos_path %></h1>
    <h3>Dale!</h3>

    <nav>
      <%= link_to "Add Video", videos_new_path %>
    </nav>
  </header>

<%= yield %>

</body>
</html>

app/views/videos/edit.html.erb
<%= render "form" %>

app/views/videos/index.html.erb
<main>
  <% @videos.each do |video| %>
  <article>
    <h4><%= link_to video.title, video.youtube_link %></h4>
    <iframe class="video-embed" width="560" height="315" src=<%= video.embed_link %> frameborder="0" allowfullscreen></iframe>
  </article>
  <% end %>
</main>

app/views/videos/new.html.erb
<%= form_for @video do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :released_on %>
  <%= f.date_select :released_on %>
  <br>
  <%= f.label :embed_url, "YouTube Id" %>
  <%= f.text_field :embed_url %>
  <br>
  <%= f.submit "Create!" %>
<% end %>

<ul>
<%   @video.errors.full_messages.each do |message| %>
  <li><%= message %></li>
<% end %>
</ul>